name: "0.1$(Rev:.r)"
variables:
  BuildConfiguration: Release

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: build/common-steps.yml
  - template: build/unit-tests-step.yml

- job: MacOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: build/common-steps.yml
  - template: build/unit-tests-step.yml

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: build/common-steps.yml
  - template: build/unit-tests-with-coverage-step.yml
