name: "0.1$(Rev:.r)"
variables:
  BuildConfiguration: Release

jobs:
- job: Linux
  variables:
    os: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - template: ci-templates/common-steps.yml
    parameters:
      OS: $(os)

- job: MacOS
  variables:
    os: MacOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - template: ci-templates/common-steps.yml
    parameters:
      OS: $(os)

- job: Windows
  variables:
    os: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: ci-templates/common-steps.yml
    parameters:
      OS: $(os)
