name: "0.1$(Rev:.r)"
variables:
  build_Configuration: Release

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: DotNetCoreCLI@2
  name: dotnetRestore
  displayName: Restore Dependencies
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  name: dotnetBuild
  displayName: Compile projects
  inputs:
    command: build
    configuration: $(build_Configuration)
    projects: '**/*.csproj'
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  name: dotnetTest
  displayName: Run tests
  inputs:
    command: test
    configuration: $(build_configuration)
    projects: tests/ArmEval.Core.Tests

- task: DotNetCoreCLI@2
  name: dotnetPublish
  displayName: Publish files
  inputs:
    command: publish
    configuration: $(build_configuration)
    arguments: '--no-restore --output $(Build.ArtifactStagingDirectory)/publish'

- task: PublishBuildArtifacts@1
  name: publishArtifacts
  displayName: Publish build artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: publish
    publishLocation: Container
