name: "0.1$(Rev:.r)"
variables:
  BuildConfiguration: Release

strategy:
  matrix:
    # linux:
    #   platform: linux
    #   imageName: 'ubuntu-16.04'
    # mac:
    #   platform: mac
    #   imageName: 'macos-10.13'
    windows:
      platform: windows
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: DotNetCoreCLI@2
  name: dotnetRestore
  displayName: Restore Dependencies
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  name: dotnetBuild
  displayName: Compile projects
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  name: dotnetTest
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: 'tests/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
