name: "0.1$(Rev:.r)"
variables:
- group: AzureConnectionData
- name: BuildConfiguration
  value: Release

strategy:
  matrix:
    linux:
      platform: linux
      imageName: 'ubuntu-16.04'
    mac:
      platform: mac
      imageName: 'macos-10.13'
    windows:
      platform: windows
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: DotNetCoreCLI@2
  name: dotnetRestore
  displayName: Restore Dependencies
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  name: dotnetBuild
  displayName: Compile projects
  inputs:
    command: build
    configuration: $(BuildConfiguration)
    projects: '**/*.csproj'
    arguments: '--no-restore'

- task: DotNetCoreCLI@2
  name: dotnetTest
  displayName: Run tests
  inputs:
    command: test
    configuration: $(BuildConfiguration)
    projects: tests/ArmEval.Core.Tests
  env:
    ArmEval_TenantId: $(TenantId)
    ArmEval_ClientId: $(ClientId)
    ArmEval_ClientSecret: $(ClientSecret)
    ArmEval_SubscriptionId: $(SubscriptionId)

- task: DotNetCoreCLI@2
  name: dotnetPublish
  displayName: Publish files
  inputs:
    command: publish
    configuration: $(BuildConfiguration)
    arguments: '--no-restore --output $(Build.ArtifactStagingDirectory)/publish'

- task: PublishBuildArtifacts@1
  name: publishArtifacts
  displayName: Publish build artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
    ArtifactName: publish-$(platform)
    publishLocation: Container
